ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
    TraceEnable Off
    LimitRequestBody 11534336

    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/log/apache2/error.log
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>

